### ISSUE TITLE
Wireless nixie tube

### ISSUE THREAD

**Issue by vety010** [Apioframe/eln1-revived#13]
The most-likely-to-get-rejected thing, but what if we could separately craft a base and the tube itself so tube would be wirelessly connected to the base, and the base and the tube together could be crafted into the nixie tube we now have

**Comment by qrmcat** [comment]
I mean, that isn't really wireless nixie tube, but I don't really see *why* we would need that.

**Comment by qrmcat** [comment]
I'd say we don't need this. Sorry.
